### ISSUE TITLE
running with provided specs throws exception

### ISSUE THREAD

**Issue by 85pando** [b3iA/ebook.js#1]
Hi there,
I wanted to have a peak at other JVerse stories. Having read HDMGP next to the main story, I find the "reading on reddit" experience suboptimal. I then stumbled upon this repo.

I am currently trying to run this in WSL2 Debian.
```sh
$ uname -a
Linux RIG-Windows 4.4.0-19041-Microsoft #3996-Microsoft Thu Jan 18 16:36:00 PST 2024 x86_64 GNU/Linux
$ cat /etc/debian_version
11.9
$ node --version
v12.22.12
$ npm -v
7.5.2
```

When I run the tool with any spec provided in the specs folder (all files are unchanged), I get the following exception.
```sh
$ node ebook.js specs/jverse-xiu-chang-saga.json
/folderToRepo/ebook.js/node_modules/marked/lib/marked.cjs:870
                    cap[0] = this.rules.inline._backpedal.exec(cap[0])?.[0] ?? '';
                                                                       ^
SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/folderToRepo/ebook.js/filters/from-local-html.js:2:16)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
```

**Comment by b3iA** [comment]
Yup, that looks like a syntax error all right, but one introduced into 'marked' - the 3rd party markdown parser ebook.js uses, and as such an issue that should be reported to that project. As an immediate mitigation strategy, I suggest downgrading the version of 'marked' you're using to one without the issue until it's fixed. Ebook.js hasn't been updated in quite a while and won't be relying on any recent features added to that module.

**Comment by 85pando** [comment]
If you need some closure: It seems to be solely a problem with WSL. It works on actual Debian and Ubuntu.
Only that (i believe) Reddit changed their API to be protected with the recent thingie ... So probably needs a scraping rewrite or something. (This is not a request. Mind you.)
